Fix README.md
The readme instructions on setting up the puma dev server are incorrect.

1. Running "brew install puma-dev" causes the following error: Error: No available formula with the name "puma-dev" 
- Instead you should run "brew install puma/puma/puma-dev" as per https://github.com/puma/puma-dev

2. "sudo puma-dev setup" is also invalid

$ sudo puma-dev setup
Error: Unknown command: setup

You need to include the hyphen: sudo puma-dev -setup

Just to make sure people don't waste time on silly mistakes like this 👍